variable "associate_public_ip_address" {}
variable "cidr" {}
variable "context_path" {}
variable "environment_type" {}
variable "instance_type" {}
variable "key_name" {}
variable "public_ip" {}
variable "public_subnet" {}
variable "region" {}
variable "s3_bucket" {}
variable "source_dest_check" {}
variable "stack_name" {}
variable "tomcat_password" {}
variable "tomcat_username" {}
variable "tomcat_users_path" {}
variable "vpc_id" {}
