module "jenkins" {
  source                      = "tf_aws_jenkins"
  associate_public_ip_address = "${var.associate_public_ip_address}"
  cidr                        = "${var.cidr}"
  environment_type            = "${var.environment_type}"
  instance_type               = "${lookup(var.instance_size, "jenkins")}"
  jenkins_email               = "${var.jenkins_email}"
  jenkins_password            = "${var.jenkins_password}"
  jenkins_username            = "${var.jenkins_username}"
  key_name                    = "${var.key_name}"
  public_ip                   = "${var.public_ip}"
  public_subnet               = "${var.public_subnet}"
  region                      = "${var.region}"
  source_dest_check           = "${var.source_dest_check}"
  stack_name                  = "${var.stack_name}"
  vpc_id                      = "${var.vpc_id}"
}
