module "tomcat" {
  source                      = "tf_aws_tomcat"
  associate_public_ip_address = "${var.associate_public_ip_address}"
  cidr                        = "${var.cidr}"
  context_path                = "${module.s3.context_path}"
  environment_type            = "${var.environment_type}"
  instance_type               = "${lookup(var.instance_size, "tomcat")}"
  key_name                    = "${var.key_name}"
  public_ip                   = "${var.public_ip}"
  public_subnet               = "${var.public_subnet}"
  region                      = "${var.region}"
  s3_bucket                   = "${module.s3.devops_bucket}"
  source_dest_check           = "${var.source_dest_check}"
  stack_name                  = "${var.stack_name}"
  tomcat_password             = "${var.tomcat_password}"
  tomcat_username             = "${var.tomcat_username}"
  tomcat_users_path           = "${module.s3.tomcat_users_path}"
  vpc_id                      = "${var.vpc_id}"
}
